name = "inncloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "inncloud-mail-db"
database_id = "3fa812fa-4972-45c1-9632-2ef320610a07"

[[kv_namespaces]]
binding = "kv"
id = "2e96ea6cc0d24b358bf3f4467676e7b8"

#[[r2_buckets]]
#binding = "r2"
#bucket_name = ""

#[[send_email]]
#name = "email"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[vars]
domain = ["mail.inncloud.top"]
admin = "admin@inncloud.top"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
